### ISSUE TITLE
Disable linting when typing

### ISSUE THREAD

**Issue by bstrahija** [php-integrator/atom-linter-legacy-php56#49]
Is there an option to only run the linter when saving a file, not all the time when typing. This seems not to be working correctly, and sometimes the same error appears twice: https://www.dropbox.com/s/qv711sg7gy2my1g/Screenshot%202016-10-18%2010.42.06.png?dl=0

**Comment by Gert-dev** [comment]
There is anoption to disable it, I believe you can find it in the settings of the `linter` package (I believe it is called "lint on the fly").

**Comment by bstrahija** [comment]
Well I'm not seeing it ;) https://www.dropbox.com/s/hz7re7hetpf4bwg/Screenshot%202016-10-19%2010.40.51.png?dl=0

**Comment by bstrahija** [comment]
I though the base linter package was the problem, but it's disabled there and still it's running the linter when typing: https://www.dropbox.com/s/hho7ptlnhren7x6/Screenshot%202016-10-19%2010.41.49.png?dl=0

**Comment by Gert-dev** [comment]
Hmmm, that might be because I'm using an "indie linter" rather than a regular linter, where I have to manage this myself. I'll mark this as enhancement.

**Comment by bstrahija** [comment]
What linter are you using? Right now it makes development seem slow since it's linting the code on every keypress and errors keep popping up all the time.

It would be fine to have a simple timeout when type of like 3-4 seconds, but ideally an option to run the linting on save would be great.

**Comment by Gert-dev** [comment]
Oh, with "indie linter" I'm referring to the type of linter that can be registered with the `linter` package. IIRC, the normal (non-indie) linter either lints on save (like what you're looking for) or on buffer change (lint on the fly).

I actually wanted to index on buffer change _after_ it also finished reindexing. For this reason, I used a so-called indie linter, which determines by itself when it has new information. The downside is that I have to manage lint on save myself.

Aside from this, seeing as linting currently happens as soon as reindexing finishes (which in turn happens as soon as the buffer stops changing), the upcoming version of the base package will allow you to increase the time it takes for a reindex to happen. This is of course not the same as what you're asking here, but it will allow you to make the issue less painful until this is implemented.

**Comment by ricpelo** [comment]
+1. It could be great if linting remains disabled when typing.

**Comment by ricpelo** [comment]
Only to clarify: it would be great if integrator linter runs only when I stop typing (after delay), just like the "Lint as you type interval" option of linter package.

**Comment by Gert-dev** [comment]
Update: this will most likely be supported in upcoming version 3.0.0 of the base package. There is still [one open issue](https://github.com/steelbrain/linter/issues/1407) that is preventing me from completing the migration on the development branch.

**Comment by tgomesfork** [comment]
Any news on this? Right now I had to disable this package, because it makes atom super slow as I'm typing. If it was just on save, it would be ok.

**Comment by Gert-dev** [comment]
Yes. With upcoming 3.0 you will be able to disable indexing continuously (and only index on save). As a result, linting will also only happen on save.

**Comment by Gert-dev** [comment]
Hello! I'm moving all relevant tickets from this repository to the base package as this functionality is now part of the base package.

Indexing continuously can now be disabled in base 3.0, allowing you to also defer linting until a save occurs.
