### ISSUE TITLE
please support linter v2

### ISSUE THREAD

**Issue by juvevood** [php-integrator/atom-linter-legacy-php56#57]
please support linter v2

**Comment by Gert-dev** [comment]
This package broke for a while when 2.0 was released, but steelbrain has released 2.1, which readds support for legacy linters, causing this package to work again. Updating to v2 is definitely on the roadmap, though.

**Comment by juvevood** [comment]
Thank you for everything you do.nice atom plugin !

**Comment by Gert-dev** [comment]
Hello! I'm moving all relevant tickets from this repository to the base package as this functionality is now part of the base package.

In base 3.0, v2 of the linter API is now being used!
